openapi: 3.0.2
info:
  description: "Lists the REST APIs provided by a toFHIR log server"
  version: "1.1"
  title: "toFHIR-log-server REST API"

servers:
  - url: "http://localhost:8086/tofhir-logs"
    description: Local deployment of the toFHIR log server


tags:
  - name: "Execution"
    description: "Represents a logical grouping for project entities"


paths:
  # Beginning of the Execution tag
  /projects/{projectId}/jobs/{jobId}/executions:
    get:
      tags:
        - Execution
      summary: Gets executions of the mapping job
      parameters:
        - $ref: "#/components/parameters/projectId"
        - $ref: "#/components/parameters/jobId"
        # Filter parameters for lazy load
        - name: page
          in: query
          required: true
          description: requested page of the executions
          schema:
            type: integer
            example: 1
        - name: dateBefore
          in: query
          required: false
          description: Executions started before this date
          schema:
            type: string
        - name: dateAfter
          in: query
          required: false
          description: Executions started after this date
          schema:
            type: string
        - name: errorStatuses
          in: query
          required: false
          description: Request type of executions written as comma seperated
          schema:
            type: string

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Execution"

  /projects/{projectId}/jobs/{jobId}/executions/{executionId}:
    get:
      tags:
        - Execution
      summary: Gets the details of the specified execution
      parameters:
        - $ref: "#/components/parameters/projectId"
        - $ref: "#/components/parameters/jobId"
        - $ref: "#/components/parameters/executionId"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Execution"
        '404':
          $ref: "#/components/responses/404NotFound"

  /projects/{projectId}/jobs/{jobId}/executions/{executionId}/logs:
    get:
      tags:
        - Execution
      summary: Gets execution logs
      parameters:
        - $ref: "#/components/parameters/projectId"
        - $ref: "#/components/parameters/jobId"
        - $ref: "#/components/parameters/executionId"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Log"
        '404':
          $ref: "#/components/responses/404NotFound"


components:
  schemas:
    Execution:
      type: object
      description: Executions of a mapping job
      properties:
        id:
          type: string
          description: "Identifier of the execution"
          example: "c531d5b0-40fc-42a9-8f2d-c6105e3a5d39"
        mappingUrls:
          type: array
          items:
            type: string
            description: "Url of the mapping runned in the execution"
            example: "https://aiccelerate.eu/fhir/mappings/pilot1/anesthesia-observations-mapping"
        startTime:
          type: string
          description: "Start time of the execution"
          example: "2024-01-26T10:19:39.538+03:00"
        errorStatus:
          type: string
          description: "Result of the the mapping job"
          enum:
            - "SUCCESS"
            - "FAILURE"
            - "PARTIAL_SUCCESS"
            - "STARTED"
    Log:
      type: object
      description: "Logs of the individual executions"
      properties:
        "@timestamp":
          type: string
          description: "Timestamp of the event"
          example: "2024-01-26T10:19:39.538+03:00"
        errorCode:
          type: string
          description: "Error code, if any"
        errorDesc:
          type: string
          description: "Error description, if any"
        errorExpr:
          type: string
          description: "Expression that causes error, if any"
        eventId:
          type: string
          description: "Identifier of the event"
          example: "MAPPING_JOB_RESULT"
        executionId:
          type: string
          description: "Identifier of the execution"
          example: "c531d5b0-40fc-42a9-8f2d-c6105e3a5d39"
        jobId:
          type: string
          description: "Identifier of the job"
          example: "pilot1"
        level:
          type: string
          description: "Level of the log"
          example: "INFO"
        logger_name:
          type: string
          description: "Name of the logger"
          example: "io.tofhir.engine.mapping.FhirMappingJobManager"
        mappedResource:
          type: string
          description: "Mapped resource, if any"
        mappingExpr:
          type: string
          description: "Mapping expression, if any"
        mappingUrl:
          type: string
          description: "URL of the mapping"
          example: "https://aiccelerate.eu/fhir/mappings/pilot1/anesthesia-observations-mapping"
        message:
          type: string
          description: "Log message"
          example: "toFHIR batch mapping result (STARTED) for execution 'c531d5b0-40fc-42a9-8f2d-c6105e3a5d39' of job 'pilot1' in project 'pilot1'"
        numOfFailedWrites:
          type: integer
          description: "Number of failed writes, -1 if there is an error"
          example: -1
        numOfFhirResources:
          type: integer
          description: "Number of written FHIR resources, -1 if there is an error"
          example: -1
        numOfInvalids:
          type: integer
          description: "Number of invalid rows, -1 if there is an error"
          example: -1
        numOfNotMapped:
          type: integer
          description: "Number of not mapped rows, -1 if there is an error"
          example: -1
        projectId:
          type: string
          description: "Identifier of the project"
          example: "pilot1"
        result:
          type: string
          description: "Result of the mapping job"
          example: "STARTED"
        source:
          type: string
          description: "Source of the error, if any"
        stack_trace:
          type: string
          description: "Stack trace of the error, if any"
        error_logs:
          type: array
          description: "Logs of the errors, if any"
          items:
            $ref: "#/components/schemas/ErrorLog"
    ErrorLog:
      type: object
      description: "Logs of the errors"
      properties:
        errorCode:
          type: string
          description: "Error code"
          example: "mapping_error"
        errorDesc:
          type: string
          description: "Error description"
          example: "FHIR path expression returns empty although value is not marked as optional! Please use '?' mark in placeholder e.g. {{? <fhir-path-expression>}} or correct your expression"
        message:
          type: string
          description: "Detailed error message"
          example: "Mapping failure (mapping_error) for job 'pilot1' and mapping 'https://aiccelerate.eu/fhir/mappings/pilot1/condition-mapping' within expression 'Expression: result. Error: FHIR path expression returns empty although value is not marked as optional! Please use '?' mark in placeholder e.g. {{? <fhir-path-expression>}} or correct your expression' execution 'c531d5b0-40fc-42a9-8f2d-c6105e3a5d39'!\n\tSource: {\"pid\":\"p1\",\"code\":\"J13\",\"codeDisplay\":\"Pneumonia due to Streptococcus pneumoniae\",\"onsetDateTime\":\"2012-10-15\",\"abatementDateTime\":null,\"encounterId\":null,\"diagnosisType\":\"main\",\"isProlonged\":true,\"certainity\":\"confirmed\",\"asserter\":null}\n\tError: FHIR path expression returns empty although value is not marked as optional! Please use '?' mark in placeholder e.g. {{? <fhir-path-expression>}} or correct your expression\n\tExpression: Hello"
        mappingUrl:
          type: string
          description: "URL of the mapping"
          example: "https://aiccelerate.eu/fhir/mappings/pilot1/condition-mapping"

  # HTTP responses for requests
  responses:
    400BadRequest:
      description: "Bad or Invalid request"
    409AlreadyExists:
      description: "Given object already exists"
    404NotFound:
      description: "Given resource does not exist"

  # Path and query parameters for requests
  parameters:
    projectId:
      in: path
      name: "projectId"
      required: true
      schema:
        type: string
        format: uuid
        pattern: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
      description: "Identifier of the project"

    jobId:
      in: path
      name: "jobId"
      schema:
        type: string
      required: true
      description: "Identifier of the job"

    executionId:
      name: executionId
      in: path
      required: true
      schema:
        type: string

    mappingUrl:
      in: path
      name: "mappingUrl"
      schema:
        type: string
        format: url
      required: true
      description: "Url of a mapping"