package io.tofhir.server.model
import akka.http.scaladsl.model.StatusCodes
import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.server.MalformedRequestContentRejection
import akka.http.scaladsl.server.{MethodRejection, RejectionHandler, UnsupportedRequestContentTypeRejection, Rejection}

object ToFhirRejectionHandler {

  /**
   * Custom rejection handler to send proper error message to front-end on rejections.
   */
  private val rejectionHandler: RejectionHandler =
    RejectionHandler.newBuilder()

      /**
       * Handles the cases type of the request data is wrong. Ex: String instead of a terminology system model.
       * supportedTypes is not worked properly in the tested cases, it only included 'application/json'
       */
      .handle {
        case UnsupportedRequestContentTypeRejection(supportedTypes) =>
          complete(StatusCodes.UnsupportedMediaType -> UnsupportedMediaType("Unsupported payload format", s"Server refuses to accept the request because the type of the request data is not in a supported format").toString)
      }

      /**
       * Handles the malformed content exception, Ex: No id field in an imported file
       * message is generated by Akka, Ex: No usable value for id
       * cause is a brief description of the exception, Ex: "Content is malformed"
       */
      .handle {
        case MalformedRequestContentRejection(message, cause) =>
          complete(StatusCodes.BadRequest -> BadRequest("Necessary field(s) is missing", message).toString)
      }

      /**
       * Handles all types of method rejections, i.e the REST method is not applicable on the given URL
       * supportedMethods are the applicable methods on the given URL
       */
      .handleAll[MethodRejection] { methodRejections =>
        val supportedMethods = methodRejections.map(_.supported.name)
        complete(StatusCodes.MethodNotAllowed -> MethodForbidden("Method not allowed", s"Server refuses to accept the request because request method is not allowed in this URL. Supported methods: ${supportedMethods.mkString(", ")}.").toString)
      }

      /**
       * Handles when the given URL is not mapped to anywhere in API
       * This case has a special representation as handleNotFound
       */
      .handleNotFound {
        extractUri { requestUrl  =>
          complete(StatusCodes.NotFound -> ResourceNotFound("Url not found", s"${requestUrl} does not exist in this API.").toString)
        }
      }

      /**
       * Handle the rest of the possible rejection types. Send the name of the rejections.
       */
      .handleAll[Rejection] { rejections =>
        val rejectionMessages = rejections.map(_.toString).mkString(", ")
        complete(StatusCodes.BadRequest -> BadRequest("Request rejected.", s"Rejections: ${rejectionMessages}"))
      }
      .result()

  def getRejectionHandler(): RejectionHandler = {
    rejectionHandler
  }

}
